# Generated by Django 3.2.12 on 2025-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_admindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Main Course', 'Main Course'), ('Appetizers', 'Appetizers'), ('Desserts', 'Desserts')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
    ]
