# Generated by Django 3.2.12 on 2025-05-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
