# Generated by Django 3.2.12 on 2025-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20250518_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Appetizers', 'Appetizers'), ('Desserts', 'Desserts')], default='Main Course', max_length=20),
        ),
    ]
