# Generated by Django 3.2.12 on 2025-05-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.userdata')),
            ],
        ),
    ]
